### ISSUE TITLE
Sorry for misusing the issues tab, but

### ISSUE THREAD

**Issue by FaultierSP** [alex-free/alex-free.github.io#1]
I needed to somehow contact you, and couldn't find any information on your site.

Something weird happened today, as I commited some files to one of my repositories. I authenticated myself per ssh-key, but your username was labeled as "author" on my commits. I managed to change author name by force pushing files, but now you are a contributor to my repository. Thanks, I guess? :) I am relatively new to using git, but I think something went wrong here.

Greets.

P.S. Weird part is: my name is Alex. Even weirder: I use the word "internets" a lot. :)

**Comment by alex-free** [comment]
> I needed to somehow contact you, and couldn't find any information on your site.
> 
> Something weird happened today, as I commited some files to one of my repositories. I authenticated myself per ssh-key, but your username was labeled as "author" on my commits. I managed to change author name by force pushing files, but now you are a contributor to my repository. Thanks, I guess? :) I am relatively new to using git, but I think something went wrong here.
> 
> Greets.
> 
> P.S. Weird part is: my name is Alex. Even weirder: I use the word "internets" a lot. :)

Double check your commit email set by git config, is it maybe my email by mistake (It's not  public because the email itself is so simple I really wish to protect it from spam, please don't post it here if it is indeed is). You can do so by:

git config --global user.email

If your not seeing your email then that's why. Or maybe it was temporarily set to mine by typo or something. Github assigns ownership of commits to username based on this value and the database in Github  (which my email is used for in question). 

I once had the user.email myself wrong and some other Alex (not you or I, can not make this up) apparently committed to my website! It was me though, and I found no way other then deleting and restarting my website repo on Github. Luckily that isn't really that important in comparison to other repos of mine.

More info here: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-email-address-for-every-repository-on-your-computer

Besides that, I'm not really sure. Maybe that helps. I am honored however to be a contributor :) :laughing:

**Comment by FaultierSP** [comment]
> Double check your commit email set by git config, is it maybe my email by mistake...

Yeah, I think it was it. I have a relatively fresh Parrot OS installation, so the git wasn't configured at all. So maybe it just grabbed my username and host of the local machine, i.e. "alex@parrot". And this somehow was enough.

I was able to change my local git settings, then 
~~~
git commit --amend -C HEAD --reset-author
git push --force
~~~
That worked, so I didn't need to create another repository.

It is so weird to me. You are mandated to 2FA and ssh-keys here (which is a good thing IMHO), but when you push, the service goes "meh, that's close enough, these are your files now, congrats".

Anyway, thanks for answering. :)
