### ISSUE TITLE
Inquiry - is there a way to copy tonyhax gameshark code file to ps1 memory card without a ps2?

### ISSUE THREAD

**Issue by VersatileNinja** [alex-free/alex-free.github.io#2]
This isn't an issue but not sure where else to post this question. I have a ps2 and it works great for copying the tonyhax gameshark cheat code file to ps1 memory card per instructions on your website.

I also have a ps3 memory card adapter as well as a picomemcardplus. 

Are there any other methods to allow a user to copy the tonyhax gameshark cheat code file to ps1 but without using a softmodded ps2?

I thought using memcardrex would help me to import the file into a MCR file, but it does not see it as a valid file.

Open to any ideas if possible. I'm typing this on my phone so forgive me for not putting the exact filename of the gameshark cheat code file.

**Comment by alex-free** [comment]
> This isn't an issue but not sure where else to post this question. I have a ps2 and it works great for copying the tonyhax gameshark cheat code file to ps1 memory card per instructions on your website.
> 
> 
> 
> I also have a ps3 memory card adapter as well as a picomemcardplus. 
> 
> 
> 
> Are there any other methods to allow a user to copy the tonyhax gameshark cheat code file to ps1 but without using a softmodded ps2?
> 
> 
> 
> I thought using memcardrex would help me to import the file into a MCR file, but it does not see it as a valid file.
> 
> 
> 
> Open to any ideas if possible. I'm typing this on my phone so forgive me for not putting the exact filename of the gameshark cheat code file.

I use the PS3MCA with memcardrex to write the GameShark save files to memory cards myself! I love the PS3MCA. It even works on Linux for me.

What you need to do is
1) Read the card with PS3MCA so that the slots are updated in memcardrex with the data on the memory card
2) Select any available unused slot and right click it. Select import save.
3) Go to the directory containing the save in the open file window of memcardrex. Note that the save won't show up when you select the folder containing the save for some reason, I'm not sure why but I'll look into it when I get time. Anyways just type in the save file name at the bottom of the open file window and click OK while in the directory containing the save. It will import the file.
4) Write to the memory card.

Let me know if that solves this.

**Comment by VersatileNinja** [comment]
FYI, I tried this on my windows machine and per your instructions, its working great! I didn't know typing in the save name file manually in the open window (doesn't seem it matters which file name extension is selected) will import the save too. I'm closing the ticket, cheers!
